### ISSUE TITLE
Textdomain as plugin slug

### ISSUE THREAD

**Issue by NateWr** [10up/grunt-wp-plugin#21]
First, thanks for this. I've been using my own grunt-init template for a while and really happy to be able to compare notes and pull in some more tricks for my own.

I noticed that you don't use the plugin [slug/filename](https://github.com/10up/grunt-wp-plugin/blob/master/rename.json#L2) as the [textdomain](https://github.com/10up/grunt-wp-plugin/blob/master/rename.json#L7). Otto has [mentioned](https://make.wordpress.org/themes/2014/10/30/team-meeting-guidelines-chat/#comment-37590) changes that are coming to the WordPress.org plugin/theme repositories to handle translation management, which would require the textdomain match the plugin slug. I made the mistake of not doing this so I will have to switch and manage backwards compatibility.

I raise this issue to a) let you know it might be worth updating this or b) benefit from hearing why not from people smarter than myself.

(ps - if anyone knows of a plugin that's switched textdomains and maintained backwards compatibility, I'd love a link!)

**Comment by ericmann** [comment]
In the beginning, the only requirement was that a _unique_ textdomain be used. Otto's blog aside, this is the first I've heard of the plugin slug being used as a textdomain. Completely open to making that change.

**Comment by kim07** [comment]
:+1:

**Comment by ericmann** [comment]
Closing for now as the plugin slug change hasn't amounted to anything yet ...
